# Generated by Django 5.2.7 on 2025-10-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('process', 'jarayonda'), ('done', 'tayyorlangan'), ('canceled', 'bekor qilingan')], default='progcess', max_length=15),
        ),
    ]
